version: '3'

services:
  api:
    container_name: dasa_api
    image: wricke/dasa_challenge
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    networks:
      - db
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./.env

  mysql:
    container_name: dasa_mysql
    image: mysql
    networks:
      - db
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - ./.env

networks:
  db:

volumes:
  mysql: